### ISSUE TITLE
Gupax v1.2.0 to-do list

### ISSUE THREAD

**Issue by hinto-janai** [hinto-janai/gupax#14]
This release will have general features/fixes and include a P2Pool v3.0+ hardfork compatible binary in the bundle.

There will be an interim Gupax v1.1.1 release including minor fixes and so that the bundle can include a post-fork P2Pool binary.

**Features:**
- [x] Embed XMRig benchmarks stats; Parse and compare with user's CPU https://github.com/hinto-janaiyo/gupax/issues/12

**Fixes:**
- [x] Add documentation on practical downsides of community nodes https://github.com/hinto-janaiyo/gupax/issues/11
- [x] Create ZMQ batch tester, replace [Community Monero Nodes](https://github.com/hinto-janaiyo/gupax#community-monero-nodes) with known ZMQ-open nodes from https://monero.fail
- [x] https://github.com/hinto-janaiyo/gupax/issues/5
- [ ] Fix low OS resolution spacing https://github.com/hinto-janaiyo/gupax/issues/13
- [x] Fix `[Status] P2Pool` spacing (stats sometimes overflow the UI)
- [x] Update community node list (trim dead/slow nodes, add more variety)
- [x] Remove `--no-color` in P2Pool command arguments, use `NO_COLOR` instead https://github.com/SChernykh/p2pool/commit/726224b25318af511d4b59f1a04b290525cb0c83  
*EDIT:* `portable_pty`'s `.env("NO_COLOR" "true")` works standalone in a test program when writing to an actual terminal but doesn't work within Gupax, the egui text console still displays ANSI codes so `--no-color` stays for now.
- [x] Fix `localhost` IP parsing https://github.com/hinto-janaiyo/gupax/issues/16

**Maybe:**
- [ ] Update egui v0.19.0 -> v0.20.1. This update includes many fixes but also has breaking UI changes and will need manual sizing adjustment of pretty much all the UI elements in Gupax
- [ ] Backup manual Monero Node & Pool. This isn't hard to add but it will affect a lot of data points (UI, disk structs, command parsing functions) and might be a little awkward to fit given the already tight UI in the P2Pool/XMRig tab 

**Tests:**
- [x] Review all unit tests, add/remove if necessary
- [x] Windows
- [x] macOS
- [x] Linux
