### ISSUE TITLE
Gupax v1.3.0 to-do list

### ISSUE THREAD

**Issue by hinto-janai** [hinto-janai/gupax#23]
Release ETA: By end of July 2023

**Features:**
- [ ] https://github.com/hinto-janai/gupax/issues/37
- [x] https://github.com/hinto-janai/gupax/issues/38
- [ ] Background/tray mode https://github.com/hinto-janai/gupax/issues/21 https://github.com/hinto-janai/gupax/pull/25
- [x] Different status color indicating P2Pool's sync status (orange)
- [x] Different status color indicating XMRig's mining status (orange)

**Fixes:**
- [x] Fix `[Status] P2Pool` spacing (stats sometimes overflow the UI)
- [x] Add more user-friendly solution messages to init failure: https://github.com/hinto-janai/gupax/blob/45d76dd402fc4d5b8b7465440ad2ff4ab08b112a/src/main.rs#L327
- [x] Handle rare indexing panics: https://github.com/hinto-janai/gupax/blob/45d76dd402fc4d5b8b7465440ad2ff4ab08b112a/src/main.rs#L425

**Maybe:**
- [x] Breaking dependency upgrades https://github.com/hinto-janai/gupax/pull/24
- [ ] https://github.com/hinto-janai/gupax/issues/27
- [x] https://github.com/hinto-janai/gupax/issues/28
- [ ] https://github.com/hinto-janai/gupax/issues/34

**Maintenance:**
- [x] [Update Remote Monero Nodes](https://github.com/hinto-janai/monero-nodes)
- [x] [Update XMRig benchmarks](https://github.com/hinto-janai/xmrig-benchmarks)

**Tests:**
- [x] Windows
- [x] macOS
- [x] Linux

**Comment by plowsof** [comment]
cool feature in the latest p2pool update. backup hosts list
https://github.com/SChernykh/p2pool/blob/v3.5/docs/COMMAND_LINE.MD#multiple-backup-hosts

**Comment by hinto-janai** [comment]
[`v1.3.0`](https://github.com/hinto-janai/gupax/releases/tag/v1.3.0)
